services:
  redis:
    image: redis:7
    container_name: fastpass-redis
    ports:
      - "6379:6379"
    restart: always

  mysql:
    image: mysql:8.0
    container_name: fastpass-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: fastpass
      MYSQL_USER: fastpass
      MYSQL_PASSWORD: fastpass1234
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always

  api:
    build: ./app
    container_name: fastpass-api
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - mysql
    restart: always

  worker:
    build: ./app
    container_name: fastpass-worker
    depends_on:
      - redis
      - mysql
    command: python -u worker.py
    restart: always


volumes:
  mysql_data: